<a href="https://colab.research.google.com/github/LBMH-lang/LBMH/blob/master/B%C3%A0i_t%E1%BA%ADp_NumPy_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
import random

In [43]:
#Bài 1:
A_0 = np.random.rand(7, 5)
print(A_0)

[[0.42755407 0.76754397 0.62907241 0.61449792 0.97714189]
 [0.09781254 0.63592815 0.83220942 0.96441747 0.43440963]
 [0.81379783 0.73987682 0.00227471 0.56475156 0.70487428]
 [0.21028972 0.30384788 0.75298566 0.81988664 0.41539522]
 [0.10263605 0.35866125 0.8178873  0.99891089 0.24721127]
 [0.27900452 0.51450856 0.34656617 0.95869272 0.45508394]
 [0.15021406 0.26523773 0.75188202 0.58899544 0.88765298]]


In [8]:
#Bài 2:
A_1 = np.zeros((6,7))
print(A_1)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [13]:
#Bài 3:
A_2 = np.random.rand(7,7)
print(A_2)

[[7.26429750e-01 8.90347847e-01 7.42589977e-01 1.07536563e-04
  8.09277693e-01 5.93638902e-01 4.63054970e-01]
 [4.99503787e-01 5.63040187e-01 5.32517013e-01 3.01101827e-01
  5.69773137e-01 2.93809232e-01 9.54558445e-01]
 [4.88525869e-01 4.17140215e-01 3.92360226e-01 4.27920856e-01
  1.35536466e-01 7.42766498e-01 9.76600357e-01]
 [3.46242282e-01 1.03304428e-01 4.87300598e-01 4.04667947e-01
  2.02568958e-01 8.07494709e-02 9.22624084e-01]
 [3.67012527e-01 4.43090539e-01 7.92517067e-02 3.96321458e-01
  8.73787525e-01 1.03337562e-01 7.44089991e-01]
 [9.89429098e-01 2.50940040e-01 2.94788552e-01 6.14303469e-01
  4.67629777e-01 5.89631466e-02 2.54417350e-01]
 [4.50140712e-01 9.41332964e-02 6.18804117e-01 7.51155756e-02
  4.69240536e-01 2.01657112e-01 9.83814439e-01]]


In [30]:
#Bài 4:
a = np.zeros((6, 6), int)
np.fill_diagonal(a, 5)
a

array([[5, 0, 0, 0, 0, 0],
       [0, 5, 0, 0, 0, 0],
       [0, 0, 5, 0, 0, 0],
       [0, 0, 0, 5, 0, 0],
       [0, 0, 0, 0, 5, 0],
       [0, 0, 0, 0, 0, 5]])

In [38]:
#Bài 5:
np.triu(np.arange(3*4*5).reshape(3, 4, 5))

array([[[ 0,  1,  2,  3,  4],
        [ 0,  6,  7,  8,  9],
        [ 0,  0, 12, 13, 14],
        [ 0,  0,  0, 18, 19]],

       [[20, 21, 22, 23, 24],
        [ 0, 26, 27, 28, 29],
        [ 0,  0, 32, 33, 34],
        [ 0,  0,  0, 38, 39]],

       [[40, 41, 42, 43, 44],
        [ 0, 46, 47, 48, 49],
        [ 0,  0, 52, 53, 54],
        [ 0,  0,  0, 58, 59]]])

In [40]:
#Bài 6:
np.tril(np.arange(3*4*5).reshape(3, 4, 5))

array([[[ 0,  0,  0,  0,  0],
        [ 5,  6,  0,  0,  0],
        [10, 11, 12,  0,  0],
        [15, 16, 17, 18,  0]],

       [[20,  0,  0,  0,  0],
        [25, 26,  0,  0,  0],
        [30, 31, 32,  0,  0],
        [35, 36, 37, 38,  0]],

       [[40,  0,  0,  0,  0],
        [45, 46,  0,  0,  0],
        [50, 51, 52,  0,  0],
        [55, 56, 57, 58,  0]]])

In [41]:
#Bài 7:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [54]:
#Bài 8:
A = np.random.rand(6, 7)
B = np.random.rand(6, 7)
print('A + B:', A + B)

x = int(input("Nhập 1 số:"))
C = np.random.rand(5, 8)
print('C * x :', C * 2)

D = np.random.rand(3, 7)
print('D^T:',np.transpose(D))

A_ = np.random.rand(5, 7)
B_ = np.random.rand(7, 3)
print('A * B : ', np.dot(A_,B_))

A_1 = np.random.rand(5, 5)
print('A^-1 : ', np.linalg.inv(A_1))

A + B: [[0.88842101 0.73894895 0.74937905 0.95141496 1.49156326 1.10268657
  1.47154836]
 [1.51972201 0.9452212  0.68729909 0.8768255  0.96229016 1.37198596
  0.86265332]
 [1.08986445 0.72198721 0.61796444 1.11863237 1.17347726 0.89178866
  0.93676643]
 [1.27932433 0.51036278 1.64830516 1.10086172 1.63608435 1.10484284
  1.03160437]
 [1.62110486 0.20883381 1.55167032 1.94573239 0.5576786  0.57071663
  1.00459132]
 [0.98018299 1.05432557 0.31574207 0.96950453 0.95432715 0.26343304
  0.66639246]]
Nhập 1 số:2
C * x : [[1.94712481 0.92675352 1.67941964 0.23239388 1.48314774 1.90156293
  0.68436445 0.9631652 ]
 [1.17744154 1.02966006 1.5576038  1.42090525 0.42114481 0.93147169
  0.17924094 1.83407483]
 [0.14909312 1.14617876 0.93623369 0.74105281 1.24188674 0.28603041
  1.84993799 0.99847768]
 [0.26525451 0.78145147 1.00886339 0.49764888 1.27844903 1.22582229
  1.99380868 0.69160889]
 [0.53299669 0.09506426 1.56986664 0.13237266 0.50715959 0.65671638
  0.00539139 0.7783774 ]]
D^T: [[0.75913

In [60]:
#Bài 9:
a1 = np.arange(8)
print('row vector:', a1)
arr = np.array([[1, 2, 3]]).T
print('columm vector:',arr)

row vector: [0 1 2 3 4 5 6 7]
columm vector: [[1]
 [2]
 [3]]
