<a href="https://colab.research.google.com/github/LBMH-lang/LBMH/blob/master/B%C3%A0i_10_T%C3%ACm_hi%E1%BB%83u_th%C6%B0_vi%E1%BB%87n_Numpy_Pandas_Matplotlib.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
A = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [3]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
B = np.array([[1,2,2], [2,3,2], [4,6,5]])

In [5]:
B

array([[1, 2, 2],
       [2, 3, 2],
       [4, 6, 5]])

In [6]:
print ('A + B: \n', A+B)
print ('A * B: \n', A*B)

A + B: 
 [[ 2  4  5]
 [ 6  8  8]
 [11 14 14]]
A * B: 
 [[ 1  4  6]
 [ 8 15 12]
 [28 48 45]]
