<a href="https://colab.research.google.com/github/LBMH-lang/LBMH/blob/master/B%C3%A0i_t%E1%BA%ADp_Numpy_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
#Bài 1:
A = np.array([5, 7, 14])
print("Giá trị của A:", A)

Giá trị của A: [ 5  7 14]


In [8]:
#Bài 2:
A1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15])
print("Giá trị của A:", A1)

Giá trị của A: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [10]:
#Bài 3:
import random
n = int(input("Nhap vao mot so n bat ky: "))
A = np.zeros((1, n), dtype = float)
A[0][0] = 2
d = -0.5
for i in range(1, n, 1):
    if(i % 2 == 1):
        A[0][i] = -1.0
    else:
        A[0][i] = A[0][i] + (i - 1)*d
print(A)

Nhap vao mot so n bat ky: 5
[[ 2.  -1.  -0.5 -1.  -1.5]]


In [23]:
#Bài 4:
OA = np.random.randint(3, 5, (2, 4))
print("Độ dài của OA:",len(OA))

Độ dài của OA: 2


In [31]:
from typing import AbstractSet
#Bài 6:
a = np.random.rand(2,3)
b = np.random.rand(2,3)
print (np.inner(a,b))

[[0.87378827 0.89362166]
 [0.35109979 0.51427287]]


In [32]:
#Bài 7:
print(np.cross(a,b))

[[-0.26534009  0.04574933  0.50098836]
 [-0.43094503  0.27874895  0.0776115 ]]


In [34]:
#Bài 8:
a1 = np.random.random(3)
print(np.transpose(a1))

[0.07334308 0.00094954 0.36912131]


In [43]:
#Bài 9:
a = [1, 2, 3, 4, 5]
b = [[1], [2], [3], [4], [5]]
print("a=",a)
print("b=",b)
A = np.array(a)
B = np.array(b)
print("Vector a:",A)
print("Vector b:",B)
print("a^T= ",np.transpose(A))
print("b^T= ",np.transpose(B))

a= [1, 2, 3, 4, 5]
b= [[1], [2], [3], [4], [5]]
Vector a: [1 2 3 4 5]
Vector b: [[1]
 [2]
 [3]
 [4]
 [5]]
a^T=  [1 2 3 4 5]
b^T=  [[1 2 3 4 5]]
