<a href="https://colab.research.google.com/github/LBMH-lang/LBMH/blob/master/B%C3%A0i_t%E1%BA%ADp_NumPy_04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import numpy as np
import random

Câu 1:

In [22]:

a0 = np.arange(-3, 4, dtype=int)
a1 = np.linspace(1.0, 5.0, num=7)
a2 = np.logspace(2.0, 3.0, num=7)
a3 = np.random.rand(7)
print('a0 =' ,a0)
print('a1 =' ,a1)
print('a2 =' ,a2)
print('a3 =' ,a3)
#Số chiều của các vector:
print('Số chiều của a0:' ,a0.ndim)
print('Số chiều của a1:' ,a1.ndim)
print('Số chiều của a2:' ,a2.ndim)
print('Số chiều của a3:' ,a3.ndim)
#Số chiều của vector chuyển vị:
a0_ = np.transpose(a0)
print('Số chiều của a0^T:' ,a0_.ndim)
a1_ = np.transpose(a1)
print('Số chiều của a1^T:' ,a1_.ndim)
a2_ = np.transpose(a2)
print('Số chiều của a2^T:' ,a2_.ndim)
a3_ = np.transpose(a3)
print('Số chiều của a3^T:' ,a3_.ndim)

a0 = [-3 -2 -1  0  1  2  3]
a1 = [1.         1.66666667 2.33333333 3.         3.66666667 4.33333333
 5.        ]
a2 = [ 100.          146.77992676  215.443469    316.22776602  464.15888336
  681.29206906 1000.        ]
a3 = [0.19081215 0.70535103 0.00630224 0.71958479 0.86058805 0.69672045
 0.2596849 ]
Số chiều của a0: 1
Số chiều của a1: 1
Số chiều của a2: 1
Số chiều của a3: 1
Số chiều của a0^T: 1
Số chiều của a1^T: 1
Số chiều của a2^T: 1
Số chiều của a3^T: 1


Câu 2:

In [34]:

A0 = np.random.rand(10,7)
A1 = np.arange(70).reshape(10, 7)

print('A0 =' ,A0)
print('A1 =' ,A1)
#Số chiều của các ma trận:
print('Số chiều của A0:' ,A0.ndim)
print('Số chiều của A1:' ,A1.ndim)
#Số chiều của vector chuyển vị:
A0_ = np.transpose(A0)
print('Số chiều của A0^T:' ,A0_.ndim)
A1_ = np.transpose(a1)
print('Số chiều của A1^T:' ,A1_.ndim)

A0 = [[0.4214017  0.4156901  0.26250085 0.5931919  0.64451568 0.37157685
  0.32926339]
 [0.16397851 0.83826246 0.23694749 0.93774244 0.78198585 0.1089181
  0.343823  ]
 [0.30651751 0.71656246 0.32705257 0.92530278 0.24345159 0.33919654
  0.44999069]
 [0.17353249 0.64758928 0.62389801 0.64923023 0.30921266 0.44580119
  0.96917971]
 [0.01825367 0.48897787 0.03834306 0.76990831 0.24983602 0.22322401
  0.46302712]
 [0.83085882 0.27718996 0.60751749 0.94823313 0.71601171 0.14981695
  0.69134394]
 [0.30804756 0.09040706 0.48656625 0.76833173 0.67302695 0.94413741
  0.71388627]
 [0.32904125 0.43583125 0.09425904 0.48442046 0.2156832  0.79410975
  0.27090742]
 [0.3763833  0.77127202 0.22647219 0.78441675 0.06432495 0.34072017
  0.33677048]
 [0.33381297 0.83661176 0.19854183 0.81729236 0.36704336 0.13017395
  0.6367145 ]]
A1 = [[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]
 [35 36 37 38 39 40 41]
 [42 43 44 45 46 47 48]
 [

Câu 3:

In [36]:

#Chuyển ma trận A ở câu 2 thành vector:
print(A0.flatten())
print(A1.flatten())


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69]
[10.          9.93877551  9.87755102  9.81632653  9.75510204  9.69387755
  9.63265306  9.57142857  9.51020408  9.44897959  9.3877551   9.32653061
  9.26530612  9.20408163  9.14285714  9.08163265  9.02040816  8.95918367
  8.89795918  8.83673469  8.7755102   8.71428571  8.65306122  8.59183673
  8.53061224  8.46938776  8.40816327  8.34693878  8.28571429  8.2244898
  8.16326531  8.10204082  8.04081633  7.97959184  7.91836735  7.85714286
  7.79591837  7.73469388  7.67346939  7.6122449   7.55102041  7.48979592
  7.42857143  7.36734694  7.30612245  7.24489796  7.18367347  7.12244898
  7.06122449  7.        ]


Câu 5:

In [49]:
A = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print('A= ',A)
print("Trung bình: ",np.mean(A, axis = 0))
print("Trung vị: ",np.median(A))
print("Phương sai: ", np.var(A))
print("Độ lệch chuẩn: ", np.std(A))

A=  [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Trung bình:  [5. 6. 7. 8.]
Trung vị:  6.5
Phương sai:  11.916666666666666
Độ lệch chuẩn:  3.452052529534663


In [54]:
A15 = np.arange(150).reshape(15,10)
print("Ma trận A: ", A15)
print('A= ',A)
print("Trung bình A: ",np.mean(A15, axis = 0))
print("Trung vị A: ",np.median(A15))
print("Phương sai A: ", np.var(A15))
print("Độ lệch chuẩn A: ", np.std(A15))

Ma trận A:  [[  0   1   2   3   4   5   6   7   8   9]
 [ 10  11  12  13  14  15  16  17  18  19]
 [ 20  21  22  23  24  25  26  27  28  29]
 [ 30  31  32  33  34  35  36  37  38  39]
 [ 40  41  42  43  44  45  46  47  48  49]
 [ 50  51  52  53  54  55  56  57  58  59]
 [ 60  61  62  63  64  65  66  67  68  69]
 [ 70  71  72  73  74  75  76  77  78  79]
 [ 80  81  82  83  84  85  86  87  88  89]
 [ 90  91  92  93  94  95  96  97  98  99]
 [100 101 102 103 104 105 106 107 108 109]
 [110 111 112 113 114 115 116 117 118 119]
 [120 121 122 123 124 125 126 127 128 129]
 [130 131 132 133 134 135 136 137 138 139]
 [140 141 142 143 144 145 146 147 148 149]]
A=  [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Trung bình A:  [70. 71. 72. 73. 74. 75. 76. 77. 78. 79.]
Trung vị A:  74.5
Phương sai A:  1874.9166666666667
Độ lệch chuẩn A:  43.300307928081374
