<a href="https://colab.research.google.com/github/LBMH-lang/LBMH/blob/master/B%C3%A0i_t%E1%BA%ADp_NumPy_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import random

Hàm numpy.apply_along_axis () giúp chúng ta áp dụng một hàm bắt buộc cho các lát cắt 1D của mảng đã cho. 

In [ ]:
#câu 1:
b = np.array([[8,1,7], [4,3,9], [5,2,6]])
np.apply_along_axis(sorted, 1, b)

array([[1, 7, 8],
       [3, 4, 9],
       [2, 5, 6]])

In [ ]:
#Câu 2:
A = np.random.rand(15, 17)
print('A = ', A)

A =  [[0.52140995 0.57075226 0.22338721 0.64638542 0.7280845  0.01772725
  0.6908773  0.92310883 0.58804106 0.33251342 0.693647   0.32761324
  0.87630929 0.5394104  0.43724663 0.11319318 0.42056256]
 [0.32837022 0.71552556 0.1436434  0.11185366 0.91044906 0.73828505
  0.98157816 0.00986929 0.1624405  0.50952059 0.32055026 0.56404328
  0.2836734  0.94657999 0.50417822 0.47198306 0.21183605]
 [0.46577782 0.00527886 0.51215593 0.84836843 0.07897856 0.18565752
  0.94476192 0.75057278 0.58551297 0.42362375 0.54992096 0.24741739
  0.81639649 0.54233751 0.36340586 0.82021186 0.94640762]
 [0.7219713  0.10774061 0.44734025 0.47790966 0.88786323 0.47293703
  0.67454736 0.34764981 0.965903   0.37964146 0.12743456 0.76117695
  0.98558232 0.12824378 0.04457473 0.53128149 0.45538794]
 [0.40936284 0.06960624 0.66389244 0.28514663 0.78671503 0.7914249
  0.62341271 0.96284505 0.58306667 0.72491555 0.26198965 0.89955432
  0.70629919 0.65054858 0.86527409 0.82665694 0.86433833]
 [0.73477471 0.56397673 0.

In [ ]:
# Câu 3:
b = np.array([[1,2,3], [4,5,6], [7,8,9]])
np.apply_along_axis(np.diag, -1, b)

array([[[1, 0, 0],
        [0, 2, 0],
        [0, 0, 3]],

       [[4, 0, 0],
        [0, 5, 0],
        [0, 0, 6]],

       [[7, 0, 0],
        [0, 8, 0],
        [0, 0, 9]]])

In [ ]:
#Câu 5:
import numpy as np
def tim_gia_tri_nho_nhat(x): return (x[0] + x[-1]) * 0.5  
y = np.array([[2,4,6], [1,3,5], [9,7,8]])
np.apply_along_axis(tim_gia_tri_nho_nhat, 1, y)

array([4. , 3. , 8.5])