<a href="https://colab.research.google.com/github/LBMH-lang/LBMH/blob/master/B%C3%A0i_t%E1%BA%ADp_2_%C3%94n_t%E1%BA%ADp_l%E1%BA%ADp_tr%C3%ACnh_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Cài Đặt thư viện Numpy

In [1]:
import numpy as np

Khởi tạo mảng một chiều


In [2]:
#Khởi tạo mảng một chiều với kiểu dữ liệu các phần tử là Integer
arr = np.array([1,3,4,5,6], dtype = int)

#Khởi tạo mảng một chiều với kiểu dữ liệu mặc định
arr = np.array([1,3,4,5,6])

print(arr)

[1 3 4 5 6]


Khởi tạo mảng hai chiều

In [3]:
arr1 = np.array([(4,5,6), (1,2,3)], dtype = int)

print(arr1)

[[4 5 6]
 [1 2 3]]


Khởi tạo mảng ba chiều

In [4]:
arr2 = np.array(([(2,4,0,6), (4,7,5,6)],
                 [(0,3,2,1), (9,4,5,6)],
                 [(5,8,6,4), (1,4,6,8)]), dtype = int)

print(arr2)

[[[2 4 0 6]
  [4 7 5 6]]

 [[0 3 2 1]
  [9 4 5 6]]

 [[5 8 6 4]
  [1 4 6 8]]]


Khởi tạo Vector

In [7]:
_a = [ 1, 2, 3, 4 ] #array-like object  
a = np.array(_a) #create a 1-dimension array (vector) from _a 
print('Vector 4 chiều:', a) #print vector a

Vector 4 chiều: [1 2 3 4]


Các toán tử với ma trận và vector

In [9]:
#Cộng trừ hai ma trận:
import numpy as np
_a = [ [ 1, 2, 3 ], [ 4, 5, 6 ] ]
_b = [ [ 2, 3, 5], [7, 9, 21] ]
a = np.array(_a) #create 2 * 3 matrix: a
b = np.array(_b) #create 2 * 3 matrix: b
print('a + b =', a + b) #print out a + b
print('a – b =', a - b) #print out a - b

a + b = [[ 3  5  8]
 [11 14 27]]
a – b = [[ -1  -1  -2]
 [ -3  -4 -15]]


In [11]:
#Nhân chia ma trận với một số:
import numpy as np
_a = [ [ 3, 2, 1 ], [ 2, 4, 6 ] ]
a = np.array(_a)
print('a / 2 =', a / 2) #print giá trị a / 2
print('a * 2 =', a * 2) #print giá trị a * 2

a / 2 = [[1.5 1.  0.5]
 [1.  2.  3. ]]
a * 2 = [[ 6  4  2]
 [ 4  8 12]]


In [13]:
#Nhân ma trận với vector:
import numpy as np
_a = [ [ 1, 2 ], [ 3, 4 ], [ 5, 6 ] ]
a = np.array(_a) #Tạo ma trận 3 * 2
_b = [ 1, 2 ]
b = np.array(_b) #Tạo vector hai chiều
print(a)
print(b)
print('a * b =', a.dot(b)) #In giá trị a * b khi dùng narray.dot()
print('a * b =', a @ b) #In giá trị a * b khi dùng @ operation

[[1 2]
 [3 4]
 [5 6]]
[1 2]
a * b = [ 5 11 17]
a * b = [ 5 11 17]


In [14]:
#Nhân ma trận với ma trận:
import numpy as np
_a = [ [ 1, 2 ], [ 3, 4 ], [ 5, 6 ] ]
a = np.array(_a) #Tạo ma trận 3 * 2 
_b = [ [1, 3], [2, 1] ]
b = np.array(_b) #Tạo ma trận 2 * 2 
print(a)
print(b)
print('a * b =', a.dot(b)) #In giá trị a * b khi dùng narray.dot()
print('a * b =', a @ b) #In giá trị a * b khi dùng @ operation

[[1 2]
 [3 4]
 [5 6]]
[[1 3]
 [2 1]]
a * b = [[ 5  5]
 [11 13]
 [17 21]]
a * b = [[ 5  5]
 [11 13]
 [17 21]]
