<a href="https://colab.research.google.com/github/LBMH-lang/LBMH/blob/master/L%C3%AA_B%C3%A1_Minh_Huy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

THƯ VIỆN NUMPY


In [9]:
import numpy as np
import random
def matran(m, n): #Hàm tạo ma trận  hàng n cột m
    #Nhập ma trận ngẫu nhiên
    a = np.random.randint(-10, 10, size= (m, n))
    #Khởi tạo ma trận 
    b = np.array([[3,1,4], [7, 5, 0]])
    
    print("Ma trận random a= ", a)
    
    print("Ma trận b= ", b)
    #Thực hiện phép cộng ma trận
    print("phép cộng ma trận: ", a+b)
    #Thực hiện phép trừ ma trận
    print("phép trừ ma trận: ", a-b)
    #Thực hiện phép nhân ma trận
    print("phép nhân ma trận: ", a*b)
    #Thực hiện phép chia ma trận
    print("chia hai ma trận: ", a/b)
    #Chuyển vị ma trận
    print(b.transpose()) 
    return (a, b)
matran(2, 3)

Ma trận random a=  [[ 3 -4  0]
 [-6  5 -3]]
Ma trận b=  [[3 1 4]
 [7 5 0]]
phép cộng ma trận:  [[ 6 -3  4]
 [ 1 10 -3]]
phép trừ ma trận:  [[  0  -5  -4]
 [-13   0  -3]]
phép nhân ma trận:  [[  9  -4   0]
 [-42  25   0]]
chia hai ma trận:  [[ 1.         -4.          0.        ]
 [-0.85714286  1.                -inf]]
[[3 7]
 [1 5]
 [4 0]]


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:19: RuntimeWarning: divide by zero encountered in true_divide


(array([[ 3, -4,  0],
        [-6,  5, -3]]), array([[3, 1, 4],
        [7, 5, 0]]))